apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
helmCharts:
- name: katakam-app
  releaseName: katakam-app
  version: 0.1.39
  repo: https://github.com/katakam/helm-charts
  valuesInline:
    name: ${{values.component_id}}
    image:
      repository: ghcr.io/katakam/${{values.component_id}}
      tag: latest
    autoscaling:
      enabled: ${{values.autoscaling}}
      minReplicas: ${{values.minReplicas}}
      maxReplicas: ${{values.maxReplicas}}
      targetCPUUtilizationPercentage: ${{values.targetCPUUtilizationPercentage}}
    resources:
      requests:
        memory: ${{values.requests_memory}}
        cpu: ${{values.requests_cpu}}
      limits:
        memory: ${{values.limits_memory}}
        cpu: ${{values.limits_cpu}}