apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: alice-web
  description: Frontend Api

  # annotations:
    # github.com/project-slug: katakam/alice-web
    # backstage.io/techdocs-ref: value
  tags:
    - web
    - apache
    - frontend
  links:
    - url: https://bob.katakam.com/user
      title: Examples Users
      icon: user
    - url: https://bob.katakam.com/group
      title: Example Group
      icon: group
    - url: https://bob.katakam.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://bob.katakam.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://bob.katakam.com/help
      title: Support
      icon: help
    - url: https://bob.katakam.com/web
      title: Website
      icon: web
    - url: https://bob.katakam.com/alert
      title: Alerts
      icon: alert
spec:
  type: website
  lifecycle: production
  owner: group:dev-team
  system: alice
  dependsOn: ['system:bob']
  apiConsumedBy: ['component:alice']
