apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bob-db
  description: Bob MySQL Dashboard

  tags:
    - database
    - data
  links:
    - url: https://bob.katakam.com/user
      title: Examples Users
      icon: user
    - url: https://bob.katakam.com/group
      title: Example Group
      icon: group
    - url: https://bob.katakam.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://bob.katakam.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://bob.katakam.com/help
      title: Support
      icon: help
    - url: https://bob.katakam.com/web
      title: Website
      icon: web
    - url: https://bob.katakam.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: group:dba-team
  system: bob
  dependsOn: ['resource:bob-db']
  apiConsumedBy: ['component:alice']
